### ISSUE TITLE
Header fonts with Bootstrap 5

### ISSUE THREAD

**Issue by zero323** [amirmasoudabdol/preferably#10]
First of all, thanks for your work!

I tested 3ae5b60 with both Bootstrap 3

![Bootstrap 3](https://user-images.githubusercontent.com/1554276/144656959-d09c542e-c591-4463-8bd6-b8172f00b6ad.png)

and Bootstrap 5

![Bootstrap 5](https://user-images.githubusercontent.com/1554276/144656835-d488632f-5ccd-4627-b763-f39fa9f10a43.png)

and in general things look great, but, subjectively speaking, headers with Bootstrap 5 are bit too much (also top margin on `h1` looks a bit off). That's not hard to fix on the user side, still might be something worth tweaking in the next release.

**Comment by amirmasoudabdol** [comment]
@zero323 I agree with you on the headers, and I have adjusted it a bit already but I'm waiting for pkgdown to stabilise after the 2.0 release then I will try to adjust it a bit more! 🙂

**Comment by zero323** [comment]
FYI https://github.com/zero323/dlt/blob/main/pkgdown/extra.css ‒ this is what I tried so far, not ideal, but will pass unless you look closely.
