### ISSUE TITLE
License and Author section on mobile in Dark Mode displays unreadably

### ISSUE THREAD

**Issue by bryce-carson** [amirmasoudabdol/preferably#12]
When the dark theme is enabled on a mobile device browsing a pkgdown site using the preferably theme, the author and license section is unreadable.

![Screenshot_20220710-151207_Chrome](https://user-images.githubusercontent.com/51974245/178162842-881ff6e0-b91b-4e36-87e8-ae3d5ee64159.jpg)

**Comment by amirmasoudabdol** [comment]
Thanks for reporting this! I will look into it! 👍🏼
