### ISSUE TITLE
Question about the toggle

### ISSUE THREAD

**Issue by maelle** [amirmasoudabdol/preferably#2]
:wave: here! When using the toggle, is it expected that new pages are still using the light theme?

**Comment by amirmasoudabdol** [comment]
Hi! 👋🏼 I don't think that's the intended behavior but it's very likely that I've messed up something! 🤔 I'm going to look it up.

**Comment by maelle** [comment]
Well I was testing it on pkgdown BS4 template so that might be my fault, I'll try again and report back!

Btw I was a bit surprised to not see the toggle in the docs (as an example, to more easily see how the website looks like in both cases).

**Comment by maelle** [comment]
I only get this locally, as my reprex actually works fine https://maelle.github.io/preferably/news/index.html

**Comment by maelle** [comment]
I suppose it's fine to close, as the local preview of a pkgdown website isn't that important.
