### ISSUE TITLE
Improve accessibility of light colour theme

### ISSUE THREAD

**Issue by EllaKaye** [amirmasoudabdol/preferably#3]
Hello Amir. Thanks for this super package! I note that you say that the colour scheme is accessible, but I find that there is insufficient contrast between the green used for links and the light background. Can I suggest that, in the light theme, you change the link colour to #11866F? I suggest that because I pick up the current green colour as #18BC9B, and #11866F is the same hue and saturation, but just a bit less bright, ensuring a contrast with the white of 4.5, making it suitable for text at 14pt+. I've attached a couple of screenshots from the ColorSlurp app demonstrating this.

I would have submitted a pull request for this, but couldn't find where that colour was set.

<img width="520" alt="Screenshot 2021-05-02 at 09 08 59" src="https://user-images.githubusercontent.com/7222491/116806630-4f271380-ab26-11eb-83cd-233357c6c084.png">
<img width="522" alt="Screenshot 2021-05-02 at 09 09 12" src="https://user-images.githubusercontent.com/7222491/116806631-50f0d700-ab26-11eb-9630-d103c249d92d.png">

**Comment by amirmasoudabdol** [comment]
Hi @EllaKaye. Thanks for your kind words, and detailed feedback. I totally agree with you. That green is too bright. I was a bit worried that your suggestion is a bit too dark, and doesn't have enough contrast with the text, but I realized that its probably the best option, and you've chosen it very carefully. Thanks! 🙏🏼

The patch is on its way!

**Comment by EllaKaye** [comment]
Hi @amirmasoudabdol. Thanks for getting onto this so fast and being open to, and incorporating, my suggestion. You're right, there is a bit of a trade off here for the green between contrast with the background and contrast with the text. The colour is suggested is the brightest it can be at that hue and saturation to ensure a contrast that's good enough against the background to be read at 14+ points. I think my suggestion is *better* but I'm not 100% sure it's *best*. I'm going to be learning more about colour accessibility on the web over the next few months and if that leads to further insights on a good colour choice here, I'll submit another issue (and now that I've seen from this commit how you've patched it this time, I can submit a pull request as well). 

Thanks again for the great package 🙏🏼. I haven't released my package yet for which I'm using `preferably` as the pkgdown theme, but once I do, I'll add it to the 'in the wild list' 😀
