### ISSUE TITLE
update `pkgdown` GHA ?

### ISSUE THREAD

**Issue by IndrajeetPatil** [amirmasoudabdol/preferably#7]
The `pkgdown` GHA has changed significantly from what it used to be, and I was wondering if the action you are using in this [repo ](https://github.com/amirmasoudabdol/preferably/blob/main/.github/workflows/pkgdown.yaml) should also be updated so that the users know how to adapt this new workflow file to successfully install `{preferably}`?

https://github.com/r-lib/actions/blob/master/.github/workflows/pkgdown.yaml

**Comment by amirmasoudabdol** [comment]
Thanks @IndrajeetPatil for bringing this to my attention. I had it that GitHub notifies me, but I think I have missed it. I'm gonna look into it!

**Comment by amirmasoudabdol** [comment]
This should be fixed. I'm using their latest template. It's slightly cleaner! 👍🏼
